# Jekyll configuration for clean URLs
permalink: /:title/
relative_links:
  enabled: true
  collections: true

# Base URL for custom domain
baseurl: ""
url: "https://younkerstudio.com"

# GitHub Pages specific settings
markdown: kramdown
highlighter: rouge
safe: true

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /:title/
