[[redirects]]
  from = "/drums"
  to = "/drums.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/resume"
  to = "/resume.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
